create table bom_configuration(
bom_configuration_id int4 not null generated by default as identity ,
bom_name varchar(100) not null,
bom_description text ,
bom_type_id int4,
project_id int4 ,
budget double precision,
is_delete boolean not null default false,
created_date timestamptz not null default now(),
updated_date timestamptz not null,
created_by int8,
updated_by int8,
constraint pk_bom_configuration primary key (bom_configuration_id),
constraint fk_bom_configuration_bom_type_id foreign key (bom_type_id) references master_data(master_data_id),
constraint fk_bom_configuration_project_id foreign key (project_id) references project(project_id)
)

alter table bom rename to bom_detail;

alter table bom_detail
add column bom_configuration_id int4;

alter table bom_detail 
add constraint fk_bom_detail_bom_configuration_id foreign key (bom_configuration_id) references bom_configuration(bom_configuration_id);
