create table user_primary_project(
user_primary_project_id int4 not null generated by default as identity ,
user_id int4,
project_id int4,
created_date timestamptz not null default now(),
updated_date timestamptz not null,
created_by int8,
updated_by int8,
constraint pk_user_primary_project primary key (user_primary_project_id),
constraint fk_user_primary_project_user_id foreign key (user_id) references users(user_id),
constraint fk_user_primary_project_project_id foreign key (project_id) references project(project_id)
)