create table user_primary_project(
user_primary_project_id int4 not null generated by default as identity ,
user_id int4,
project_id int4,
created_date timestamptz not null default now(),
updated_date timestamptz not null,
created_by int8,
updated_by int8,
constraint pk_user_primary_project primary key (user_primary_project_id),
constraint fk_user_primary_project_user_id foreign key (user_id) references users(user_id),
constraint fk_user_primary_project_project_id foreign key (project_id) references project(project_id)
)

create table project_member_association(
project_member_association_id int4 not null generated by default as identity,
project_id int4 not null,
user_id int4 not null,
project_role_id int4,
access_start_date date,
access_end_date date,
is_delete boolean not null default false,
created_date timestamptz not null default now(),
updated_date timestamptz ,
created_by int8,
updated_by int8,
constraint pk_project_member_association primary key (project_member_association_id),
constraint fk_project_member_association_project_id foreign key (project_id) references project(project_id),
constraint fk_project_member_association_user_id foreign key (user_id) references users(user_id),
constraint fk_project_member_association_project_role_id foreign key (project_role_id) references master_data(master_data_id)
)