CREATE TABLE machinery ( 
machinery_id int4 not null generated by default as identity ,
machinery_name VARCHAR(255) not null, 
machinery_model VARCHAR(50),
machinery_type VARCHAR(50),
manufacturer VARCHAR(255), 
date_of_purchase DATE,
warranty_expired_on DATE,
operational_status varchar(50),
location VARCHAR(255),
rate double precision,
uom_id int4,
is_delete boolean not null default false,
created_date timestamptz not null default now(),
updated_date timestamptz not null ,
created_by int8,
updated_by int8,
constraint pk_machinery primary key (machinery_id),
constraint fk_machinery_uom_id foreign key (uom_id) references uom(uom_id)
);

alter table "bom" 
add column machinery_id int4;

alter table "bom" 
add constraint fk_bom_machinery_id foreign key (machinery_id) references machinery(machinery_id);


create table labour(
labour_id int4 not null generated by default as identity ,
labour_type varchar(100) not null,
quantity int4 ,
rate double precision ,
total double precision,
uom_id int4,
is_delete boolean not null default false,
created_date timestamptz not null default now(),
updated_date timestamptz not null ,
created_by int8,
updated_by int8,
constraint pk_labour primary key (labour_id),
constraint fk_labour_uom_id foreign key (uom_id) references uom(uom_id)
)

alter table uom 
add column uom_type varchar(10);

alter table labour 
drop column rate;

alter table labour 
drop column total;

alter table labour 
drop column quantity;

alter table labour 
add column rate double precision;