version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    ports:
      - "8080:80"
  backend:
    build:
      context: .
      dockerfile: ./apps/Api/Dockerfile
    ports:
      - "3000:3000"
