--sub_category
alter table sub_category 
add column project_id int4;

alter table sub_category 
add constraint fk_sub_category_project_id foreign key (project_id) references project(project_id);

--sub_sub_category
alter table sub_sub_category 
add column project_id int4;

alter table sub_sub_category 
add constraint fk_sub_sub_category_project_id foreign key (project_id) references project(project_id);

alter table sub_sub_category 
add column parent_sub_sub_category_id int4;

alter table sub_sub_category 
add constraint fk_sub_sub_category_parent_sub_sub_category_id foreign key (parent_sub_sub_category_id) references sub_sub_category(sub_sub_category_id);

CREATE TABLE bom (
    bom_id int4 not null generated by default as identity ,
    bom_name VARCHAR(255) NOT NULL,
    quantity int4,
    uom_id int4,
    category_id int4,
    sub_category_id int4,
    sub_sub_category_id int4,
    item_id int4,
    is_delete boolean not null default false,
    created_date timestamptz NOT null default now(),
    updated_date timestamptz NOT NULL,
    created_by int8,
    updated_by int8,
    constraint pk_bom primary key bom_id,
    constraint fk_bom_uom_id foreign key (uom_id) references uom(uom_id),
    constraint fk_bom_category_id foreign key (category_id) references category(category_id),
    constraint fk_bom_sub_category_id foreign key (sub_category_id) references sub_category(sub_category_id),
    constraint fk_bom_sub_sub_category_id foreign key (sub_sub_category_id) references sub_sub_category(sub_sub_category_id),
    constraint fk_bom_item_id foreign key (item_id) references item(item_id)
);

-- alter table "bom" 
-- rename column create_date to created_date;

-- alter table "bom" 
-- rename column update_date to updated_date;