create table vendor(
vendor_id int4 not null generated by default as identity ,
vendor_name varchar(100) not null ,--The name of the vendor or company --ABC Supplies
contact_person varchar(50) null,--The primary point of contact at the vendor's company -- Vignesh AD
contact_email varchar(100),--The email address for contacting the vendor --vignesh.ad@aalamsoft.com
contact_phone_no varchar(20),--The phone number for contacting the vendor. -- +91 8776881092
address jsonb,--The physical address of the vendor's location -- address
tax_id varchar(50),--The tax identification number of the vendor for tax purposes --IN123456789
payment_terms text,-- The agreed-upon payment terms for transactions with the vendor --Net 30 Days		
preferred_payment_method_id int4,--The preferred method of payment for the vendor -- (e.g., bank transfer, check).
bank_account_details jsonb,-- Information about the vendor's bank account for electronic payments.--ABC Supplies Bank, Account #12345	
currency varchar(10),--The currency in which transactions with the vendor are conducted -- INR , USD...
vendor_category_id int4,--The category or type of products/services the vendor provides (e.g., raw materials, services, equipment).----Raw Materials id as master_data	
lead_time varchar(20),--The time it takes for the vendor to fulfill orders after receiving them. -- 10 days	
minimum_order_quantity int4,--The minimum quantity that must be ordered from the vendor. -- 100 	
notes text,--Any additional notes or comments related to the vendor. --Supplier of raw materials
is_delete boolean not null default false,
created_date timestamptz not null default now(),
updated_date timestamptz ,
created_by int8,
updated_by int8,
constraint pk_vendor primary key (vendor_id),
constraint fk_vendor_vendor_category_id foreign key (vendor_category_id) references master_data(master_data_id),
constraint fk_vendor_vendor_preferred_payment_method_id foreign key (preferred_payment_method_id) references master_data(master_data_id)
)