create table capability (
	capability_id int4 not null generated by default as identity,
	capability_name varchar(50) not null,
	description varchar(300),
	permission_type varchar(80) ,
	ui_type varchar(40),
	is_delete boolean not null default false,
	created_date timestamptz not null default now(),
	updated_date timestamptz not null,
	created_by int8,
	updated_by int8,
	constraint pk_capability primary key (capability_id)
);


create table permissions (
	permission_id int4 not null generated by default as identity,
	is_create boolean not null default false,
	is_update boolean not null default false,
	is_read boolean not null default false,
	is_visible boolean not null default false,
	capability_id int4,
	role_id int4,
	is_delete boolean not null default false,
	created_date timestamptz not null default now(),
	updated_date timestamptz not null,
	created_by int8,
	updated_by int8,
	constraint pk_permissions primary key (permission_id),
	constraint fk_permissions_capability_id foreign key (capability_id) references capability(capability_id),
	constraint fk_permissions_role_id foreign key (role_id) references role(role_id)
);

